### ISSUE TITLE
Geometry Column

### ISSUE THREAD

**Issue by slewuk** [lutraconsulting/qgis-constraint-checker-plugin#1]
Geometry column has been changed to wkb_geometry in the configuration. However, I am still getting this error when checking the constraints:

ProgrammingError: column "geom" does not exist.

I tested this in both QGIS 2.0.1 and 2.4, both 64bit on a Windows 8 Machine.

**Comment by saberraz** [comment]
I can confirm that...a serious bug IMHO.

**Comment by saberraz** [comment]
fixed in #2
